/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VendaCarrosClientes;

/**
 *
 * @author Kevin
 */
public class ComprarCarro extends javax.swing.JFrame {

    /**
     * Creates new form ComprarCarro
     */
    public ComprarCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        FormaPagamento = new javax.swing.JComboBox<>();
        Pesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CampoPesquisa = new javax.swing.JTextField();
        QuantidadeProdutos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TotalProduto = new javax.swing.JTextField();
        Cancelar = new javax.swing.JButton();
        Calcular = new javax.swing.JButton();
        FinalizarCompra = new javax.swing.JButton();
        ComboboxCarros = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setText("Veiculos Bones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setText("Qual A forma de pagamento");

        FormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartão de Crédito", "Boleto Bancário", "PIX", "PicPay" }));

        Pesquisar.setText("Pesquisar");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        jLabel2.setText("Escolha o seu Carro");

        jLabel5.setText("Quantidade");

        jLabel4.setText("Total");

        Cancelar.setBackground(new java.awt.Color(0, 0, 153));
        Cancelar.setForeground(new java.awt.Color(102, 255, 255));
        Cancelar.setText("Cancelar Compra");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Calcular.setBackground(new java.awt.Color(0, 0, 153));
        Calcular.setForeground(new java.awt.Color(102, 255, 255));
        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        FinalizarCompra.setBackground(new java.awt.Color(0, 0, 153));
        FinalizarCompra.setForeground(new java.awt.Color(102, 255, 255));
        FinalizarCompra.setText("Finalizar Compra");
        FinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompraActionPerformed(evt);
            }
        });

        ComboboxCarros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jeep Renegade Sport 1.8 4x2 Flex 16v Aut", "Chevrolet Onix Hatch Joy 1.0 8v Flex 5p Mec", "Chevrolet Prisma Sed. Lt 1.4 8v Flexpower 4p", "Chevrolet Spin Activ7 1.8 8v Econo.flex 5p Aut", "Volvo XC90", "Porsche 911 GT3 RS 992", "Chevrolet Camaro 6.2 SS" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ComboboxCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuantidadeProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pesquisar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(FormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(FinalizarCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Calcular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pesquisar)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantidadeProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboboxCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addComponent(Calcular)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TotalProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FinalizarCompra)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed

    }//GEN-LAST:event_PesquisarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CancelarActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        //calc();
    }//GEN-LAST:event_CalcularActionPerformed

    private void FinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompraActionPerformed
        /*calc();
        dispose();
        Notinha notinha = new Notinha();
        notinha.setVisible(true);*/
    }//GEN-LAST:event_FinalizarCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprarCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField CampoPesquisa;
    private javax.swing.JButton Cancelar;
    private javax.swing.JComboBox<String> ComboboxCarros;
    private javax.swing.JButton FinalizarCompra;
    private javax.swing.JComboBox<String> FormaPagamento;
    private javax.swing.JButton Pesquisar;
    private javax.swing.JTextField QuantidadeProdutos;
    private javax.swing.JTextField TotalProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public void calc(){
        double quantidade = Double.parseDouble(QuantidadeProdutos.getText());  

        double produto1 = 72900.00;
        double produto2 = 56900.00;
        double produto3 = 67900.00;
        double produto4 = 61900.00;
        double produto5 = 675950.00;
        double produto6 = 1920000.00;
        double produto7 = 417900.00;
       /* double produto8 = 72900000.00;
        double produto9 = 14900.00;
        double produto10 = 27900.00;
        double produto11= 69900.00;
        double produto12 = 215900.00;
        double produto13 = 69900.00;
        double produto14= 55900.00;
        double produto15 = 67900.00; */ 
         
        
    if(ComboboxCarros.getSelectedItem().equals("Jeep Renegade Sport 1.8 4x2 Flex 16v Aut")){
       String Resultado1;
        double res1;
        res1 = (quantidade * produto1);
        Resultado1 = String.valueOf(res1);
        TotalProduto.setText(Resultado1);
        String add1 = String.valueOf(produto1);
        }
     if(ComboboxCarros.getSelectedItem().equals("Chevrolet Onix Hatch Joy 1.0 8v Flex 5p Mec")){
        String Resultado2;
        double res2;
        res2 = (quantidade * produto2);
        Resultado2 = String.valueOf(res2);
        TotalProduto.setText(Resultado2);
        String add2 = String.valueOf(produto2);
        }
     if(ComboboxCarros.getSelectedItem().equals("Chevrolet Prisma Sed. Lt 1.4 8v Flexpower 4p")){
        String Resultado3;
        double res3;
        res3 = (quantidade * produto3);
        Resultado3 = String.valueOf(res3);
        TotalProduto.setText(Resultado3);
        String add3 = String.valueOf(produto3);
        }
    if(ComboboxCarros.getSelectedItem().equals("Chevrolet Spin Activ7 1.8 8v Econo.flex 5p Aut")){
        String Resultado4;
        double res4;
        res4 = (quantidade * produto4);
        Resultado4 = String.valueOf(res4);
        TotalProduto.setText(Resultado4);
        String add4 = String.valueOf(produto4);
        }
     if(ComboboxCarros.getSelectedItem().equals("Volvo S90")){
        String Resultado5;
        double res5;
        res5 = (quantidade * produto5);
        Resultado5 = String.valueOf(res5);
        TotalProduto.setText(Resultado5);
        String add5 = String.valueOf(produto5);
        }
     if(ComboboxCarros.getSelectedItem().equals("Porsche 911 GT3 RS 992")){
        String Resultado6;
        double res6;
        res6 = (quantidade * produto6);
        Resultado6 = String.valueOf(res6);
        TotalProduto.setText(Resultado6);
        String add6 = String.valueOf(produto6);
        }
    if(ComboboxCarros.getSelectedItem().equals("Chevrolet Camaro 6.2 SS")){
        String Resultado7;
        double res7;
        res7 = (quantidade * produto7);
        Resultado7 = String.valueOf(res7);
        TotalProduto.setText(Resultado7);
        String add7 = String.valueOf(produto7);
        }
    /* if(ComboboxCarros.getSelectedItem().equals("Fiat Strada 1.4 Cd Hard Working")){
        String Resultado8;
        double res8;
        res8 = (quantidade * produto8);
        Resultado8 = String.valueOf(res8);
        TotalProduto.setText(Resultado8);
        String add8 = String.valueOf(produto8);
        }
     if(ComboboxCarros.getSelectedItem().equals("Volkswagen Santana 1.8 Mi")){
        String Resultado9;
        double res9;
        res9 = (quantidade * produto9);
        Resultado9 = String.valueOf(res9);
        TotalProduto.setText(Resultado9);
        String add9 = String.valueOf(produto9);
        }
    if(ComboboxCarros.getSelectedItem().equals("Fiat Siena 1.0/ex 1.0 Mpi Fire/fire Flex 8v")){
       String Resultado10;
        double res10;
        res10 = (quantidade * produto10);
        Resultado10 = String.valueOf(res10);
        TotalProduto.setText(Resultado10);
        String add10 = String.valueOf(produto10);
        }
     if(ComboboxCarros.getSelectedItem().equals("Volkswagen Fusca Null")){
       String Resultado11;
        double res11;
        res11 = (quantidade * produto11);
        Resultado11 = String.valueOf(res11);
        TotalProduto.setText(Resultado11);
        String add11 = String.valueOf(produto11);
        }
     if(ComboboxCarros.getSelectedItem().equals("Toyota Hilux Cd Srx 4x4 2.8 Tdi 16v Diesel Aut")){
       String Resultado12;
        double res12;
        res12 = (quantidade * produto12);
        Resultado12 = String.valueOf(res12);
        TotalProduto.setText(Resultado12);
        String add12 = String.valueOf(produto12);
        }
    if(ComboboxCarros.getSelectedItem().equals("Ford F-1000 Ss")){
       String Resultado13;
        double res13;
        res13 = (quantidade * produto13);
        Resultado13 = String.valueOf(res13);
        TotalProduto.setText(Resultado13);
        String add13 = String.valueOf(produto13);
        }
     if(ComboboxCarros.getSelectedItem().equals("Citroën Aircross Live 1.5 Flex 8v 5p Mec.")){
       String Resultado14;
        double res14;
        res14 = (quantidade * produto14);
        Resultado14 = String.valueOf(res14);
        TotalProduto.setText(Resultado14);
        String add14 = String.valueOf(produto14);
        }
     if(ComboboxCarros.getSelectedItem().equals("Kia Sportage 4x2 Mt Lx 2.0 4p")){
       String Resultado15;
        double res15;
        res15 = (quantidade * produto15);
        Resultado15 = String.valueOf(res15);
        TotalProduto.setText(Resultado15);
        String add15 = String.valueOf(produto15);
     } */

    }

}
